-- Auto-generated from schema-map-postgres.yaml (map@74ce4f4)
-- engine: postgres
-- table:  merkle_anchors

CREATE TABLE IF NOT EXISTS merkle_anchors (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  merkle_root_id BIGINT NOT NULL,
  anchor_type TEXT NOT NULL,                   -- 'file','blockchain','notary'
  anchor_ref  VARCHAR(512) NOT NULL,
  anchored_at TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  meta JSONB NULL,
  CONSTRAINT chk_anchor_type CHECK (anchor_type IN ('file','blockchain','notary')),
  CONSTRAINT uq_merkle_anchor_ref UNIQUE (anchor_ref, anchor_type, merkle_root_id)
);
